export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  ACCOUNTANT: 'ACCOUNTANT',
  CASHIER: 'CASHIER',
  COOK: 'COOK',
  WAITER: 'WAITER',
}

export const ORDER_SOURCE = {
  WAITER: 'WAITER',
  QR: 'QR',
}

export const TABLE_GUEST_SOURCE = {
  WAITER: 'WAITER',
  QR: 'QR',
}

export const TABLE_GUEST_STATUS = {
  ACTIVE: 'ACTIVE',
  CLOSED: 'CLOSED',
}

export const ORDER_STATUS = {
  DRAFT: 'DRAFT',
  PENDING_WAITER_APPROVAL: 'PENDING_WAITER_APPROVAL',
  APPROVED: 'APPROVED',
  SENT_TO_KITCHEN: 'SENT_TO_KITCHEN',
  PREPARING: 'PREPARING',
  READY: 'READY',
  DELIVERED: 'DELIVERED',
  CLOSED: 'CLOSED',
  CANCELLED: 'CANCELLED',
}

export const KITCHEN_TICKET_STATUS = {
  PENDING: 'PENDING',
  PREPARING: 'PREPARING',
  READY: 'READY',
  DELIVERED: 'DELIVERED',
}

export const PAYMENT_METHOD = {
  CASH: 'CASH',
  TRANSFER: 'TRANSFER',
}

export const SERVICE_MODE = {
  DINE_IN: 'DINE_IN',
  TAKEAWAY: 'TAKEAWAY',
}

export const SPLIT_MODE = {
  TABLE_TOTAL: 'TABLE_TOTAL',
  SPLIT: 'SPLIT',
}

export const TABLE_STATUS = {
  FREE: 'FREE',
  OCCUPIED: 'OCCUPIED',
}

export const QR_STATUS = {
  PENDING: 'PENDING',
  GENERATED: 'GENERATED',
  PRINTED: 'PRINTED',
}

export const CASH_STATUS = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
}

export const BILL_STATUS = {
  OPEN: 'OPEN',
  PARTIALLY_PAID: 'PARTIALLY_PAID',
  PAID: 'PAID',
  CANCELLED: 'CANCELLED',
}

export const FINANCE_ACCOUNT_TYPE = {
  CASH: 'CASH',
  BANK: 'BANK',
  DIGITAL: 'DIGITAL',
}

export const FINANCE_TRANSACTION_TYPE = {
  INCOME: 'INCOME',
  EXPENSE: 'EXPENSE',
  TRANSFER: 'TRANSFER',
}

export const PRICE = {
  DEFAULT_MENU: 10,
  EXTRA_ENTRY: 3,
  TAKEAWAY_FEE_PER_MENU: 1,
}

export const KITCHEN_STATUS_TO_ORDER_STATUS = {
  PENDING: ORDER_STATUS.SENT_TO_KITCHEN,
  PREPARING: ORDER_STATUS.PREPARING,
  READY: ORDER_STATUS.READY,
  DELIVERED: ORDER_STATUS.DELIVERED,
}

export const VALID_ORDER_STATUSES = new Set(Object.values(ORDER_STATUS))
export const VALID_KITCHEN_STATUSES = new Set(Object.values(KITCHEN_TICKET_STATUS))
export const VALID_PAYMENT_METHODS = new Set(Object.values(PAYMENT_METHOD))
export const VALID_SERVICE_MODES = new Set(Object.values(SERVICE_MODE))
export const VALID_SPLIT_MODES = new Set(Object.values(SPLIT_MODE))
export const VALID_QR_STATUSES = new Set(Object.values(QR_STATUS))
export const VALID_BILL_STATUSES = new Set(Object.values(BILL_STATUS))

